# SuperMean Frontend Dockerfile
FROM node:18-alpine
#FROM node:20-alpine
# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY SuperMean/frontend/package*.json ./

# Install dependencies
RUN npm ci
RUN npm audit fix

# Copy frontend code
COPY SuperMean/frontend/ ./

# Build the application
RUN npm run build

# Expose port
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]